### PR TITLE
Fix plugin manager verifyRunning function to avoid false positives, which lead to failure to start the plugin manager. Fixes #4507

### LINKED ISSUE #4507: Occasional "Error: Reattachment process not found" when starting Steampipe in service mode
**Describe the bug**
`steampipe service start` sometimes fails to start and outputs the error:
```
Error: Reattachment process not found
```
This appears to be a race condition related to the [plugin manager](https://github.com/turbot/steampipe/tree/develop/pkg/pluginmanager), even with no plugins installed. The issue becomes more frequent in environments with many concurrent containerized instances and limited compute resources.

We came across this situation in our customized setup for automated scans of AWS accounts in our organization. For each AWS account we scan, we deploy a Docker container in an AWS Fargate ECS cluster. We've observed that this issue occurs when approx. 15 or more containers are running in parallel. Each container first starts the Steampipe service and then runs a Powerpipe benchmark, however, this benchmark frequently fails because of this bug. A minimal reproducible example is provided below, which I have tried with versions 1.0.1 through 1.1.0.

**Steampipe version (`steampipe -v`)**
v1.1.0 (current)

**To reproduce**
A minimal Docker-based example has been created to reliably reproduce the issue and capture `TRACE` level logs.

`Dockerfile`:
```sh
FROM amazonlinux:2023

ENV STEAMPIPE_VERSION="1.1.0"

RUN yum -y update && \
    yum -y install tar shadow-utils && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN curl -fsSL https://steampipe.io/install/steampipe.sh | bash -s -- "v${STEAMPIPE_VERSION}"

ENV STEAMPIPE_UPDATE_CHECK=false
ENV STEAMPIPE_TELEMETRY=none

RUN adduser --system --user-group --create-home --shell /bin/false steampipe
USER steampipe
WORKDIR /home/steampipe

# reduce later startup time
RUN steampipe service start
RUN steampipe service stop

COPY entrypoint.sh .

ENTRYPOINT ["./entrypoint.sh"]
```

`entrypoint.sh`:
```sh
#!/bin/bash

echo "[$CONTAINER_ID] steampipe service start"

export STEAMPIPE_LOG_LEVEL=TRACE
steampipe service start 1>stdout.log 2>stderr.log

if [ $? -ne 0 ]; then
    echo "[$CONTAINER_ID] $(cat stderr.log)"
    mkdir "/shared_output/failed/$CONTAINER_ID/"
    cp -r ~/.steampipe/logs/ "/shared_output/failed/$CONTAINER_ID/"
else
    mkdir "/shared_output/successful/$CONTAINER_ID/"
    cp -r ~/.steampipe/logs/ "/shared_output/successful/$CONTAINER_ID/"
fi
```

`run.sh`:
```sh
#!/bin/bash

# increase if necessary to reproduce the issue
MAX_CONTAINERS=50

OUTPUT_DIR="logs/$(date +%Y-%m-%d_%H-%M-%S)"
mkdir -p "$OUTPUT_DIR/successful"
mkdir -p "$OUTPUT_DIR/failed"

echo "[*] Starting $MAX_CONTAINERS containers"
for i in $(seq -w 1 $MAX_CONTAINERS); do
    docker run --rm -e CONTAINER_ID=$i -v "$(realpath "$OUTPUT_DIR"):/shared_output" steampipe-reattachment-bug &
done

wait
echo "[*] All containers have stopped"
echo "[*] Compare 'failed' and 'successful' Steampipe logs in $(realpath "$OUTPUT_DIR") for each container"
```

To test:
```sh
docker build -t steampipe-reattachment-bug .
./run.sh
```

**Expected behavior**

All containers should start without errors.

**Observed behavior**
Some containers fail with:
```
[*] Starting 50 containers
[48] steampipe service start
[18] steampipe service start
[28] steampipe service start
...
[27] Error: Reattachment process not found
[29] Error: Reattachment process not found
[*] All containers terminated
...
```

**Additional context**
A failed `steampipe-$(date).log` will show:
```
steampipe [d768]: failed to connect to plugin manager: Reattachment process not found
steampipe [d768]: StopDB invoker service, force false
steampipe [d768]: shutting down plugin manager
steampipe [d768]: pluginmanager.Stop start
steampipe [d768]: pluginmanager.stop start
steampipe [d768]: failed to connect to plugin manager: Reattachment process not found
steampipe [d768]: pluginmanager.stop end
steampipe [d768]: pluginmanager.Stop end
steampipe [d768]: shut down plugin manager
steampipe [d768]: stopping DB Service
steampipe [d768]: stopped DB Service
```

Whereas a successful one ends with:
```
steampipe [08bf]: start: started plugin manager, pid 84
```

This points to a plugin manager startup race condition. Potentially relevant code:
- [pluginmanager/lifecycle.go](https://github.com/turbot/steampipe/blob/96959081b01009378dd77bc64f579608b77ea8a8/pkg/pluginmanager/lifecycle.go#L79C1-L80C1)
- [pluginmanager/plugin_manager_client.go](https://github.com/turbot/steampipe/blob/96959081b01009378dd77bc64f579608b77ea8a8/pkg/pluginmanager/plugin_manager_client.go#L52)

### PR DESCRIPTION
**Pull request by kaidaguerre**
pluginmanager.State.verifyRunning() now checks the process corresponding to the pid is a plugin manager process
pluginmanager.State.kill() deletes the plugin manager state file even if the process is not found

### CODE REVIEW

**Review by pskrbasu — APPROVED** [review]

File: pkg/pluginmanager/state.go [hunk 1]
```diff
@@ -90,18 +95,42 @@ func (s *State) reattachConfig() *plugin.ReattachConfig {
...
 
 // check whether the plugin manager is running
-func (s *State) verifyRunning() bool {
-	pidExists := utils.PidExists(s.Pid)
-	return pidExists
+func (s *State) verifyRunning() (bool, error) {
+	log.Printf("[TRACE] verify plugin manager running, pid: %d", s.Pid)
+	p, err := utils.FindProcess(s.Pid)
+	if err != nil {
+		log.Printf("[TRACE] error finding process %d: %s", s.Pid, err)
```
Comment (pdecat) [inline pkg/pluginmanager/state.go:102]: Hi @kaidaguerre, shouldn't this be logged at `WARN` or `ERROR` level?
