### PR TITLE
Fixes issue where mod installation would fail silently for unmet dependencies in top mod in force mode. Closes #3358

### LINKED ISSUE #3358: `mod install --force` fails silently if there are unmet dependencies in the top mod and already installed transitive dependencies

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: pkg/modinstaller/mod_installer.go [hunk 1]
```diff
@@ -183,11 +183,11 @@ func (i *ModInstaller) InstallWorkspaceDependencies(ctx context.Context) (err er
 		}
 	}()
 
-	if err := workspaceMod.Require.ValidateSteampipeVersion(workspaceMod.Name()); err != nil {
-		return err
-	}
-	if err := workspaceMod.Require.ValidatePluginVersions(workspaceMod.Name(), i.installedPlugins); err != nil {
-		return err
+	if err := workspaceMod.ValidateRequirements(i.installedPlugins); len(err) > 0 {
```
Comment (kaidaguerre) [inline pkg/modinstaller/mod_installer.go:186]: do not use `err` as the variable name for an error slice!
use `validationErrors`

File: pkg/modinstaller/mod_installer.go [hunk 2]
```diff
@@ -183,11 +183,11 @@ func (i *ModInstaller) InstallWorkspaceDependencies(ctx context.Context) (err er
...
+		if !i.force {
```
Comment (kaidaguerre) [inline pkg/modinstaller/mod_installer.go:187]: comment: if force is set...

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
