### PR TITLE
Fix for driver prefix showing up in `check` errors. Closes #474

### LINKED ISSUE #474: Remove "pq: " from sql errors in `check`
image

### PR DESCRIPTION
**Pull request by binaek89**

### CODE REVIEW

File: control/execute/control_run.go [hunk 1]
```diff
@@ -201,12 +201,17 @@ func (r *ControlRun) addResultRow(row *ResultRow) {
...
 func (r *ControlRun) SetError(err error) {
-	r.Error = err
+	r.runError = utils.TransformErrorToSteampipe(err)
+
 	// update error count
 	r.Summary.Error++
 	r.setRunStatus(ControlRunError)
 }
 
+func (r *ControlRun) GetError() error {
```
Comment (kaidaguerre) [inline control/execute/control_run.go:211]: any reason to use a get function instead of keeping RunError public?

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
