### PR TITLE
Fixes issue where using any meta command would load connection state even if not required. Closes #3614

### LINKED ISSUE #3614: `metacommand` executions in interactive prompt should not always query for `connection state`
Most `.cmd` do not need the connection state, but query for it never-the-less

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: pkg/interactive/interactive_client.go [hunk 1]
```diff
@@ -524,23 +524,17 @@ func (c *InteractiveClient) executeMetaquery(ctx context.Context, query string)
...
 	}
 	client := c.client()
-
-	// load connection state and put into input
-	connectionState, err := c.getConnectionState(ctx)
-	if err != nil {
-		// swallow error - it may just be that we are connected to a server which does not support connection state
-		log.Println("[TRACE] failed to load connection state - are we connected to a server running a previous steampipe version?", err)
-	}
+	getter := c.getConnectionState
```
Comment (kaidaguerre) [inline pkg/interactive/interactive_client.go:527]: do we need a variable - could this just be declared inline on line 537

File: pkg/interactive/metaquery/handler_inspect.go [hunk 2]
```diff
@@ -198,12 +212,16 @@ func showStateSummaryTable(connectionState steampipeconfig.ConnectionStateMap) {
 	display.ShowWrappedTable(header, rows, &display.ShowWrappedTableOptions{AutoMerge: false})
 }
 
-func inspectQualifiedTable(connectionName string, tableName string, input *HandlerInput) error {
+func inspectQualifiedTable(ctx context.Context, connectionName string, tableName string, input *HandlerInput) error {
 	header := []string{"column", "type", "description"}
 	var rows [][]string
 
+	connectionStateMap, err := input.GetConnectionStateMap(context.TODO())
```
Comment (kaidaguerre) [inline pkg/interactive/metaquery/handler_inspect.go:219]: pass context in

File: pkg/interactive/metaquery/handler_inspect.go [hunk 3]
```diff
@@ -18,7 +19,11 @@ import (
 // inspect
 func inspect(ctx context.Context, input *HandlerInput) error {
 	// if there is no connection state in the input, call legacy inspect
```
Comment (kaidaguerre) [inline pkg/interactive/metaquery/handler_inspect.go:21]: move/delete comment

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

**Review by kaidaguerre — APPROVED** [review]
