### PR TITLE
Fixes issue where connections would get dropped in the interactive prompt. Closes #3781

### LINKED ISSUE #3781: Interactive prompt should use a connection pool limited to 1 persistent connection

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: pkg/interactive/interactive_client.go [hunk 1]
```diff
@@ -811,5 +811,6 @@ func (c *InteractiveClient) handleConnectionUpdateNotification(ctx context.Conte
 	c.executionLock.Lock()
 	defer c.executionLock.Unlock()
 
-	c.client().RefreshSessions(ctx)
+	session := c.client().RefreshSessions(ctx)
+	session.Session.Close(true)
```
Comment (kaidaguerre) [inline pkg/interactive/interactive_client.go:815]: what is this doing? why is it needed>
