### PR TITLE
Fix for `plugin list` `panic`. Closes #984

### LINKED ISSUE #984: `plugin list` fails with `panic`

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: steampipeconfig/connection_updates.go [hunk 1]
```diff
@@ -32,31 +30,30 @@ func newConnectionUpdates() *ConnectionUpdates {
...
-	ConnectionOptions *options.Connection
-	DeclRange         hcl.Range
+	Connection *modconfig.Connection
 }
 
 func (p *ConnectionData) Equals(other *ConnectionData) bool {
-	connectionOptionsEqual := (p.ConnectionOptions == nil) == (other.ConnectionOptions == nil)
-	if p.ConnectionOptions != nil {
-		connectionOptionsEqual = p.ConnectionOptions.Equals(other.ConnectionOptions)
+	if p.Connection == nil || other.Connection == nil {
```
Comment (kaidaguerre) [inline steampipeconfig/connection_updates.go:41]: implement equals on connection

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: steampipeconfig/connection_updates.go (hunk 1 above)
Comment (binaek) [reply steampipeconfig/connection_updates.go:40]: pushed

File: steampipeconfig/connection_updates.go [hunk 2]
```diff
@@ -32,31 +29,25 @@ func newConnectionUpdates() *ConnectionUpdates {
...
+		// and this file gets written in the new format in the process
+		return false
 	}
 
 	return p.Plugin == other.Plugin &&
 		p.CheckSum == other.CheckSum &&
-		p.ConnectionName == other.ConnectionName &&
-		connectionOptionsEqual &&
-		reflect.DeepEqual(p.ConnectionConfig, other.ConnectionConfig)
+		p.Connection == other.Connection
```
Comment (kaidaguerre) [inline steampipeconfig/connection_updates.go:50]: does this work or dies it compare pointers?
