### PR TITLE
Fixes issue where `data-dir` was being removed instead of it's contents during `init`. Closes #639

### LINKED ISSUE #639: `init` should remove `data-dir` contents and not the `data-dir`

### PR DESCRIPTION
**Pull request by binaek89**

### CODE REVIEW

File: utils/remove_dir_contents.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package utils
+
+import (
+	"os"
+	"path/filepath"
+)
+
+func RemoveDirectoryContents(removePath string) error {
```
Comment (kaidaguerre) [inline utils/remove_dir_contents.go:8]: if removePath does not exist, what happens?
