### PR TITLE
Fix issue where schema extraction is broken for remote services. Closes #1497

### LINKED ISSUE #1497: Schema extraction is broken for remote databases
When extracting connections, `steampipe` looks up the local config

This approach WILL not work for remote connections

Schema extraction should be independent of local config

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: db/db_local/local_db_client.go [hunk 1]
```diff
@@ -154,8 +154,90 @@ func (c *LocalDbClient) ContructSearchPath(ctx context.Context, requiredSearchPa
 	return c.client.ContructSearchPath(ctx, requiredSearchPath, searchPathPrefix, currentSearchPath)
 }
 
-func (c *LocalDbClient) GetSchemaFromDB(ctx context.Context, schemas []string) (*schema.Metadata, error) {
-	return c.client.GetSchemaFromDB(ctx, schemas)
+func (c *LocalDbClient) GetSchemaFromDB(ctx context.Context) (*schema.Metadata, error) {
```
Comment (kaidaguerre) [inline db/db_local/local_db_client.go:157]: add comment to explain why local  db has a different implementation

File: db/db_local/local_db_client.go [hunk 2]
```diff
@@ -154,8 +154,90 @@ func (c *LocalDbClient) ContructSearchPath(ctx context.Context, requiredSearchPa
...
+	// (pass nil for connection state - this forces NewConnectionSchemaMap to load it)
+	connectionSchemaMap, err := steampipeconfig.NewConnectionSchemaMap()
+	if err != nil {
+		return nil, err
+	}
+	// get the unique schema - we use this to limit the schemas we load from the database
+	schemas := connectionSchemaMap.UniqueSchemas()
+	query := c.buildSchemasQuery(schemas)
+
+	acquireSessionResult := c.AcquireSession(ctx)
```
Comment (kaidaguerre) [inline db/db_local/local_db_client.go:168]: why do we need to acquire session here, but the base implementation just calls 

```
connection, err := c.dbClient.Conn(ctx)
```

File: db/db_local/local_db_client.go [hunk 3]
```diff
@@ -154,8 +154,90 @@ func (c *LocalDbClient) ContructSearchPath(ctx context.Context, requiredSearchPa
...
+	searchPath, err := c.GetCurrentSearchPath(ctx)
+	if err != nil {
+		return nil, err
+	}
+	metadata.SearchPath = searchPath
+
+	return metadata, nil
+}
+
+func (c *LocalDbClient) populateSchemaMetadata(schemaMetadata *schema.Metadata, connectionSchemaMap steampipeconfig.ConnectionSchemaMap) {
```
Comment (kaidaguerre) [inline db/db_local/local_db_client.go:197]: add function comment
```
// update schemaMetadata to add in all other schemas which have the same schemas as those we have loaded
// NOTE: this mutates 	schemaMetadata
```

File: db/db_local/local_db_client.go [hunk 4]
```diff
@@ -154,8 +154,90 @@ func (c *LocalDbClient) ContructSearchPath(ctx context.Context, requiredSearchPa
...
+			exemplarSchema = make(map[string]schema.TableSchema)
+		}
+
+		for _, s := range otherSchemas {
+			schemaMetadata.Schemas[s] = exemplarSchema
+		}
+	}
+}
+
+func (c *LocalDbClient) buildSchemasQuery(hintSchemas []string) string {
```
Comment (kaidaguerre) [inline db/db_local/local_db_client.go:213]: what are hintSchemas?

just call it `schemas`

File: db/db_local/local_db_client.go [hunk 5]
```diff
@@ -154,8 +154,90 @@ func (c *LocalDbClient) ContructSearchPath(ctx context.Context, requiredSearchPa
...
+			// should can happen in the case of a dynamic plugin with no tables - use empty schema
+			exemplarSchema = make(map[string]schema.TableSchema)
+		}
+
+		for _, s := range otherSchemas {
+			schemaMetadata.Schemas[s] = exemplarSchema
+		}
+	}
+}
+
```
Comment (kaidaguerre) [inline db/db_local/local_db_client.go:212]: function comment to explain why this is different from the base version

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: db/db_local/local_db_client.go (hunk 2 above)
Comment (binaek) [reply db/db_local/local_db_client.go:168]: This is because `dbClient` is not a public property in the `DbClient` struct

File: db/db_local/local_db_client.go [hunk 6]
```diff
@@ -194,6 +196,8 @@ func (c *LocalDbClient) GetSchemaFromDB(ctx context.Context) (*schema.Metadata,
 	return metadata, nil
 }
 
+// update schemaMetadata to add in all other schemas which have the same schemas as those we have loaded
+// NOTE: this mutates 	schemaMetadata
```
Comment (kaidaguerre) [inline db/db_local/local_db_client.go:200]: feel free to remove the extra spaces from my suggested comment

File: db/db_local/local_db_client.go [hunk 7]
```diff
@@ -154,8 +154,94 @@ func (c *LocalDbClient) ContructSearchPath(ctx context.Context, requiredSearchPa
...
+			exemplarSchema = make(map[string]schema.TableSchema)
+		}
+
+		for _, s := range otherSchemas {
+			schemaMetadata.Schemas[s] = exemplarSchema
+		}
+	}
+}
+
+func (c *LocalDbClient) buildSchemasQuery(exemplarSchemas []string) string {
```
Comment (kaidaguerre) [inline db/db_local/local_db_client.go:217]: just `schemas` will be fine

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
