### PR TITLE
validate database name if `STEAMPIPE_INITDB_DATABASE_NAME` is used. Closes #1065

### LINKED ISSUE #1065: validate database name if `STEAMPIPE_INITDB_DATABASE_NAME` is used
postgres database name must start with a lower case character or a number. Validate this and show useful error if validation fails

### PR DESCRIPTION
**Pull request by pskrbasu**
Screenshot 2021-11-03 at 9 36 05 PM

### CODE REVIEW

File: db/db_local/install.go [hunk 1]
```diff
@@ -257,6 +257,20 @@ func runInstall(firstInstall bool, spinner *spinner.Spinner) error {
...
+	// validate db name
+	firstCharacter := databaseName[0:1]
+	var ascii int
+	for _, r := range databaseName {
+		ascii = int(r)
+		break
+	}
+	if firstCharacter == "_" {
+		log.Printf("[TRACE] valid database name: %s", databaseName)
+	} else if ascii >= 97 && ascii <= 122 {
```
Comment (kaidaguerre) [inline db/db_local/install.go:269]: could this be 
```
ascii >= 'a' && ascii <= 'z' {
```

Comment (pskrbasu) [reply db/db_local/install.go]: Done

File: db/db_local/install.go [hunk 2]
```diff
@@ -257,6 +257,20 @@ func runInstall(firstInstall bool, spinner *spinner.Spinner) error {
...
 	// resolve the name of the database that is to be installed
 	databaseName := resolveDatabaseName()
+	// validate db name
+	firstCharacter := databaseName[0:1]
+	var ascii int
+	for _, r := range databaseName {
+		ascii = int(r)
+		break
+	}
+	if firstCharacter == "_" {
```
Comment (kaidaguerre) [inline db/db_local/install.go:267]: actually lets combine them
```
if firstCharacter == "_" ||  ascii >= 'a' && ascii <= 'z' {
```
