### PR TITLE
Handle `context canceled` error during control runs. Closes #757

### LINKED ISSUE #757: context canceled error during control runs
`ERROR: context canceled`, when am running the full OCI compliance mod (steampipe check all ) where as it simply works when executing separately  steampipe check benchmark.cis_v110_2 ,

### PR DESCRIPTION
**Pull request by pskrbasu**
### NOTE

The following steps should be followed before merging this PR:

1. Merge https://github.com/turbot/steampipe-postgres-fdw/pull/90 and publish a new FDW version.
2. Merge https://github.com/turbot/steampipe-plugin-chaos/pull/52 which creates a new chaos table to simulate the `context canceled` issue which would help us in adding acceptance tests. Publish a new chaos plugin version.
3. Update the `FdwVersion` in [db.go](https://github.com/turbot/steampipe/blob/main/constants/db.go#L26) to the new FDW version.
4. Merge this test.

### CODE REVIEW

File: control/controlexecute/control_run.go [hunk 1]
```diff
@@ -127,8 +130,28 @@ func (r *ControlRun) Start(ctx context.Context, client db_common.Client) {
...
 	queryResult, err := client.Execute(ctx, query, false)
 	if err != nil {
+		// is this an rpc EOF error - meaning that the plugin somehow crashed
+		if strings.Contains(err.Error(), pluginCrashErrorSubString) {
+			if r.attempts > constants.MaxControlRunAttempts {
+				// if exceeded max retries.
+				r.SetError(fmt.Errorf("max retry attempts exceeded"))
+				return
+			}
+			// set a log line in the database logs for convenience
```
Comment (kaidaguerre) [inline control/controlexecute/control_run.go:144]: remove unneeded comment
`// set a log line in the database logs for convenience`

File: control/controlexecute/control_run.go [hunk 2]
```diff
@@ -127,8 +130,28 @@ func (r *ControlRun) Start(ctx context.Context, client db_common.Client) {
...
 
+	const pluginCrashErrorSubString = "error reading from server: EOF"
+
 	queryResult, err := client.Execute(ctx, query, false)
 	if err != nil {
+		// is this an rpc EOF error - meaning that the plugin somehow crashed
+		if strings.Contains(err.Error(), pluginCrashErrorSubString) {
+			if r.attempts > constants.MaxControlRunAttempts {
+				// if exceeded max retries.
+				r.SetError(fmt.Errorf("max retry attempts exceeded"))
```
Comment (kaidaguerre) [inline control/controlexecute/control_run.go:141]: just return original error

File: control/controlexecute/control_run.go [hunk 3]
```diff
@@ -127,8 +130,28 @@ func (r *ControlRun) Start(ctx context.Context, client db_common.Client) {
...
+				return
+			}
+			// set a log line in the database logs for convenience
+			// pass 'true' to disable spinner
+			_, _ = client.ExecuteSync(ctx, "-- Retrying...", true)
+			// increment attempt counter
```
Comment (kaidaguerre) [inline control/controlexecute/control_run.go:147]: remove `// increment attempt counter` - it's self evident

File: control/controlexecute/control_run.go [hunk 4]
```diff
@@ -127,8 +130,28 @@ func (r *ControlRun) Start(ctx context.Context, client db_common.Client) {
...
+			r.attempts++
+			// retry within the same context,
```
Comment (kaidaguerre) [inline control/controlexecute/control_run.go:149]: put this comment on 1 or 2 lines

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
