### PR TITLE
Fixes issue where multiple 'service start' would error even on same listen params. Closes #3861

### LINKED ISSUE #3861: `steampipe service start --dashboard` after a `steampipe service start` fails.
Throws the error: `Error: service is already running and listening on [127.0.0.1 192.168.<redacted>.<redacted>] - cannot change listen addresses while it's running`

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: pkg/db/db_local/running_info.go [hunk 1]
```diff
@@ -19,28 +20,30 @@ const RunningDBStructVersion = 20220411
...
-	ListenAddresses []string          `json:"listen"`
-	Port            int               `json:"port"`
-	Invoker         constants.Invoker `json:"invoker"`
-	Password        string            `json:"password"`
-	User            string            `json:"user"`
-	Database        string            `json:"database"`
-	StructVersion   int64             `json:"struct_version"`
+	Pid                     int               `json:"pid"`
+	ResolvedListenAddresses []string          `json:"resolved_listen"`
+	GivenListenAddresses    []string          `json:"given_listen"`
```
Comment (kaidaguerre) [inline pkg/db/db_local/running_info.go:25]: maybe `raw_listen` in the json?

File: pkg/db/db_local/start_services.go [hunk 2]
```diff
@@ -101,6 +101,14 @@ func StartServices(ctx context.Context, listenAddresses []string, port int, invo
 		}
 	} else {
 		res.Status = ServiceAlreadyRunning
+
+		// if the service is already running, also load the state of the plugin manager
+		pmState, err := pluginmanager.LoadState()
```
Comment (kaidaguerre) [inline pkg/db/db_local/start_services.go:106]: pluginManagerState

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
