### PR TITLE
Fix asff-json template line spacing and make templates more readable. Closes #1323

### LINKED ISSUE #1323: Fix asff-json template line spacing and make templates more readable
Fix 'asff-json' template line spacing and make templates more readable.

### PR DESCRIPTION
**Pull request by pskrbasu**

### CODE REVIEW

File: cmd/check.go [hunk 1]
```diff
@@ -468,6 +469,19 @@ func parseExportArg(arg string) (formatter controldisplay.Formatter, targetFileN
 	if formatter, found = controldisplay.GetDefinedExportFormatter(arg); found {
 		return
 	}
+
+	// no defined formatter
+	// HACK to resolve CSV and JSON filename exports
+	// We need this till we build out the templates for CSV and JSON
+	ext := filepath.Ext(arg)
+	if strings.HasSuffix(ext, "csv") {
```
Comment (kaidaguerre) [inline cmd/check.go:477]: why not 
```
if ext == constants.CsvExtension 
```

and 
```
if ext == constants.JsonExtension && !strings.HasSuffix(arg, "asff.json")
```

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: cmd/check.go (hunk 1 above)
Comment (binaek) [reply cmd/check.go:477]: `ext == constants.CsvExtension` 
can't do this, since `golang` keeps the preceding `.` in the output of `filepath.Ext`

File: cmd/check.go [hunk 2]
```diff
@@ -480,7 +480,7 @@ func parseExportArg(arg string) (formatter controldisplay.Formatter, targetFileN
 	if strings.HasSuffix(ext, "json") && !strings.HasSuffix(arg, "asff.json") {
 		return controldisplay.JSONFormatter{}, arg, nil
 	}
-	// HACK ends
+	// fix ends
```
Comment (kaidaguerre) [inline cmd/check.go:483]: remove - unneeded
