### PR TITLE
Fixes issue where interactive prompt autocomplete dropdown was showing connections in error. Closes #3628

### LINKED ISSUE #3628: Interactive prompt autocomplete shows connections which are in error.
Screenshot 2023-06-28 at 5 06 27 PM
Screenshot 2023-06-28 at 5 11 56 PM

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: pkg/steampipeconfig/connection_state.go [hunk 1]
```diff
@@ -92,13 +92,16 @@ func (d *ConnectionState) CanCloneSchema() bool {
...
 func (d *ConnectionState) Error() string {
 	return typehelpers.SafeString(d.ConnectionError)
-
 }
 
 func (d *ConnectionState) SetError(err string) {
 	d.ConnectionError = &err
 }
 
+func (d *ConnectionState) IsStateError() bool {
```
Comment (kaidaguerre) [inline pkg/steampipeconfig/connection_state.go:101]: don't think this is needed

File: pkg/interactive/interactive_client_autocomplete.go [hunk 2]
```diff
@@ -60,6 +61,11 @@ func (c *InteractiveClient) initialiseSchemaAndTableSuggestions(connectionStateM
 	firstConnectionPerPluginLookup[c.schemaMetadata.TemporarySchemaName] = struct{}{}
 
 	for schemaName, schemaDetails := range c.schemaMetadata.Schemas {
+		if connectionState, found := connectionStateMap[schemaName]; found && connectionState.IsStateError() {
```
Comment (kaidaguerre) [inline pkg/interactive/interactive_client_autocomplete.go:64]: shouldn't this be 
`connectionState.State != constants.ConnectionStateReady`

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
