### PR TITLE
Fix issue where `check` progress report `<0` running when facing errors. Closes #1131

### LINKED ISSUE #1131: control progress counters show negative values when errors occur
image

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: control/controlexecute/control_run.go [hunk 1]
```diff
@@ -171,22 +170,25 @@ func (r *ControlRun) Execute(ctx context.Context, client db_common.Client) {
 	r.Lifecycle.Add("queued_for_session")
 	dbSession, err := client.AcquireSession(ctx)
 	if err != nil {
+		if utils.IsCancelledError(err) {
```
Comment (binaek) [inline control/controlexecute/control_run.go:173]: Because we have extra `Execute`s running, `client.AcquireSession` may fail with a `Context.Cancelled`

Comment (kaidaguerre) [reply control/controlexecute/control_run.go:173]: maybe change this to 
```
if !utils.IsCancelledError(err){
    err = fmt.Errorf("error acquiring database connection, %s", err.Error())
}
r.SetError(err)
return
```

File: control/controlexecute/progress.go [hunk 2]
```diff
@@ -39,11 +39,11 @@ func (p *ControlProgressRenderer) Start() {
 	defer p.updateLock.Unlock()
 
 	if p.enabled {
-		p.spinner = display.ShowSpinner("Starting controls")
+		p.spinner = display.ShowSpinner("Starting controls...")
```
Comment (kaidaguerre) [inline control/controlexecute/progress.go:42]: we show starting controls twice - can the first one be changed to `Initializing...`

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
