### PR TITLE
Fixes issue where an empty spinner is shown. Closes #3378

### LINKED ISSUE #3378: `spinner` shows up even if there's no `message`/`status` set

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: pkg/statushooks/spinner.go [hunk 1]
```diff
@@ -24,9 +24,10 @@ const minSpinnerWidth = 7
 
 // StatusSpinner is a struct which implements StatusHooks, and uses a spinner to display status messages
 type StatusSpinner struct {
-	spinner *spinner.Spinner
-	cancel  chan struct{}
-	delay   time.Duration
+	spinner      *spinner.Spinner
+	cancel       chan struct{}
+	delay        time.Duration
+	spinnerShown bool
```
Comment (kaidaguerre) [inline pkg/statushooks/spinner.go:30]: maybe `visible`

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
