### PR TITLE
Fixes issue where '.inspect' would panic for long column descriptions. Closes #3709

### LINKED ISSUE #3709: .inspect breaks for v0.21.0-alpha.1
**Describe the bug**

`.inspect`  >> Works
`.inspect azure`  - Breaks
`.inspect connection_name`  >> .inspect azure_nagraj_aaa >> Breaks
`.inspect connection_name.table_name ` >> .inspect azure_newwarriors_aaa.azure_subnet (works) where .inspect azure_newwarriors_aaa.azure_app_configuration breaks (Inconsistent)
`.inspect table_name`  >> .inspect azure_subscription >> Mostly breaks

Note v0.20.9 version works fine.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: pkg/display/display.go [hunk 1]
```diff
@@ -139,11 +139,9 @@ func getColumnSettings(headers []string, rows [][]string, opts *ShowWrappedTable
 
 	// now that all columns are set to the widths that they need,
 	// set the last one to occupy as much as is available - no more - no less
-	const MaxWidth = 200
 	sumOfRest := sumOfAllCols - colConfigs[len(colConfigs)-1].WidthMax
-	widthConstraint := utils.NewRangeConstraint(sumOfAllCols, MaxWidth)
 	// get the max cols width
-	maxCols := GetMaxCols(widthConstraint)
+	maxCols := GetMaxCols()
```
Comment (kaidaguerre) [inline pkg/display/display.go:144]: this no longer takes `widthConstraint` into account?

Comment (binaek) [reply pkg/display/display.go:144]: No. This was never really necessary here. `GetMaxCols` returns the maximum available columns.

We use the `constrain` in `check` `table format`. There we have moved the check one-level up.

**Review by kaidaguerre — APPROVED** [review]
