### PR TITLE
Fixes issue where installing a 'non-latest' plugin will not install config even if it's not there. Closes #1660

### LINKED ISSUE #1660: Update default config file during plugin install.
If the plugin getting installed is not the `latest` tagged version, then the `config.spc` in the plugin artifact needs to be modified to have the exact tag in the `plugin` property before writing to the `config` directory.

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: ociinstaller/plugin.go [hunk 1]
```diff
@@ -126,18 +128,60 @@ func installPluginConfigFiles(image *SteampipeImage, tempdir string) error {
...
+	substitution := fmt.Sprintf(`$1 plugin = "$2@%s"`, stream)
+
+	srcScanner := bufio.NewScanner(strings.NewReader(string(src)))
+	srcScanner.Split(bufio.ScanLines)
+	destBuffer := bytes.NewBufferString("")
+
+	for srcScanner.Scan() {
+		line := srcScanner.Text()
+		if regex.MatchString(line) {
+			fmt.Println("match with", line)
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:176]: what is this printLn for?

File: ociinstaller/plugin.go [hunk 2]
```diff
@@ -126,18 +128,60 @@ func installPluginConfigFiles(image *SteampipeImage, tempdir string) error {
...
+			line = regex.ReplaceAllString(line, substitution)
+		}
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:178]: once we have found a match, can we stop scanning?

File: ociinstaller/plugin.go [hunk 3]
```diff
@@ -126,18 +128,60 @@ func installPluginConfigFiles(image *SteampipeImage, tempdir string) error {
...
 
+	if err = os.WriteFile(destFile, transformedData, inputStat.Mode()); err != nil {
+		return fmt.Errorf("writing to output file failed: %s", err)
+	}
 	return nil
 }
 
-func pluginInstallDir(imageRef string) string {
-	ref := NewSteampipeImageRef(imageRef)
+func transform(src []byte, ref *SteampipeImageRef) []byte {
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:160]: give a more informative name - renamePlugin

File: ociinstaller/plugin.go [hunk 4]
```diff
@@ -126,18 +128,60 @@ func installPluginConfigFiles(image *SteampipeImage, tempdir string) error {
...
+	_, _, stream := ref.GetOrgNameAndStream()
+	if stream == "latest" {
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:162]: move this check to outside the function - then the renamed function name will make sense

File: ociinstaller/plugin.go (hunk 3 above)
Comment (kaidaguerre) [reply ociinstaller/plugin.go:160]: only better than that :)

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: ociinstaller/plugin.go [hunk 5]
```diff
@@ -149,20 +149,18 @@ func copyConfigFileUnlessExists(sourceFile string, destFile string, ref *Steampi
 		return fmt.Errorf("couldn't read source file permissions: %s", err)
 	}
 	// transform
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:151]: better comment

File: ociinstaller/plugin.go [hunk 6]
```diff
@@ -149,20 +149,18 @@ func copyConfigFileUnlessExists(sourceFile string, destFile string, ref *Steampi
...
-
+	inputData = addPluginStreamToConfig(inputData, ref, "latest")
 	if err = os.WriteFile(destFile, inputData, inputStat.Mode()); err != nil {
 		return fmt.Errorf("writing to output file failed: %s", err)
 	}
 	return nil
 }
 
-func addPluginStreamToConfig(src []byte, ref *SteampipeImageRef) []byte {
+func addPluginStreamToConfig(src []byte, ref *SteampipeImageRef, nopIfStream string) []byte {
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:159]: comment - what does this function do?

explain what and why

File: ociinstaller/plugin.go [hunk 7]
```diff
@@ -149,20 +149,18 @@ func copyConfigFileUnlessExists(sourceFile string, destFile string, ref *Steampi
...
 	_, _, stream := ref.GetOrgNameAndStream()
+	if stream == nopIfStream {
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:161]: `nopIfStream`????

File: ociinstaller/plugin.go [hunk 8]
```diff
@@ -126,18 +128,59 @@ func installPluginConfigFiles(image *SteampipeImage, tempdir string) error {
...
+
+	srcScanner := bufio.NewScanner(strings.NewReader(string(src)))
+	srcScanner.Split(bufio.ScanLines)
+	destBuffer := bytes.NewBufferString("")
+
+	for srcScanner.Scan() {
+		line := srcScanner.Text()
+		if regex.MatchString(line) {
+			line = regex.ReplaceAllString(line, substitution)
+			line = line[1:]
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:176]: why?

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: ociinstaller/plugin.go [hunk 9]
```diff
@@ -148,17 +148,21 @@ func copyConfigFileUnlessExists(sourceFile string, destFile string, ref *Steampi
 	if err != nil {
 		return fmt.Errorf("couldn't read source file permissions: %s", err)
 	}
-	// transform
-	inputData = addPluginStreamToConfig(inputData, ref, "latest")
+	inputData = addPluginStreamToConfig(inputData, ref)
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:151]: // update the connection config with the correct plugin version

File: ociinstaller/plugin.go [hunk 10]
```diff
@@ -148,17 +148,21 @@ func copyConfigFileUnlessExists(sourceFile string, destFile string, ref *Steampi
...
 	if err = os.WriteFile(destFile, inputData, inputStat.Mode()); err != nil {
 		return fmt.Errorf("writing to output file failed: %s", err)
 	}
 	return nil
 }
 
-func addPluginStreamToConfig(src []byte, ref *SteampipeImageRef, nopIfStream string) []byte {
+// The default config files have the plugin set to the latest stream
```
Comment (kaidaguerre) [inline ociinstaller/plugin.go:158]:
```
// The default config files have the plugin set to the 'latest' stream (as this is what is installed by default)
// When installing non-latest plugins, that property needs to be adjusted to the stream actually getting installed. 
// Otherwise, during plugin resolution, it will resolve to an incorrect plugin instance
// (or none at at all, if  'latest' versions isn't installed)

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: ociinstaller/plugin.go (hunk 8 above)
Comment (binaek) [reply ociinstaller/plugin.go:180]: This is because in the substitution `regex` I had to put in an extra space to isolate the substitution token `$1`. Removing it here.

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
