### PR TITLE
steampipe service should not fail in debian:buster-slim while running in ssl mode closes #625

### LINKED ISSUE #625: steampipe service should not fail in debian:buster-slim while running in ssl mode
**Describe the bug**
`steampipe service start` was falling in debian:buster-slim with error 

```
Auto configuration failed
139973180692160:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
139973180692160:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139973180692160:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
139973180692160:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
2021-07-14 22:33:06.173 UTC [17] LOG:  database system is shut down
```

It doesn't create problems when running in non-SSL mode.

**Steampipe version (`steampipe -v`)**
Built from main

**To reproduce**
Run steampipe service start in a debian:buster

**Expected behavior**
Steampipe service should not fail

### PR DESCRIPTION
**Pull request by abhiturbot**

### CODE REVIEW

File: db/start_database.go [hunk 1]
```diff
@@ -187,7 +187,17 @@ func StartDB(port int, listen StartListenType, invoker Invoker, refreshConnectio
...
 
-	postgresCmd.Env = append(os.Environ(), fmt.Sprintf("STEAMPIPE_INSTALL_DIR=%s", constants.SteampipeDir))
+	// This is particularly required for debian:buster
+	// https://github.com/kelaberetiv/TagUI/issues/787
+	// For other os the env variable OPENSSL_CONF
+	// does not matter so its safe to put
+	// this in env variable
+	// Tested in amazonlinux, debian:buster, ubuntu, mac
+	if os.Getenv("OPENSSL_CONF") == "" {
+		postgresCmd.Env = append(os.Environ(), fmt.Sprintf("STEAMPIPE_INSTALL_DIR=%s", constants.SteampipeDir), "OPENSSL_CONF=/etc/ssl")
```
Comment (abhiturbot) [inline db/start_database.go:197]: `/etc/ssl` should I move this to constants?

Comment (binaek89) [reply db/start_database.go:197]: Yes

Comment (binaek89) [reply db/start_database.go:197]: Maybe update this to:
```
postgresCmd.Env = append(os.Environ(), fmt.Sprintf("STEAMPIPE_INSTALL_DIR=%s", constants.SteampipeDir))
if _,exists := os.LookupEnv("OPENSSL_CONF"); !exists {
    postgresCmd.Env = append(os.Environ(), "OPENSSL_CONF=/etc/ssl"
}
```
