### PR TITLE
Fixes issue where 'pg_dump' and 'pg_restore' depends on system libraries instead of packaged ones. Closes #1972

### LINKED ISSUE #1972: postgres binaries should use libraries from the installation and not the system
In some circumstances, `pg_dump` and `pg_restore` are using `libpq` that is installed in the system. This may fail, since `steampipe` may be installed in systems where there's not `postgres` pre-installed.

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: db/db_local/backup.go [hunk 1]
```diff
@@ -376,3 +380,55 @@ func getTableOfContentsFromBackup(ctx context.Context) ([]string, error) {
...
+		ctx,
+		pgRestoreBinaryExecutablePath(),
+		args...,
+	)
+	log.Println("[TRACE] pg_restore command:", cmd.String())
+	addLDPath(ctx, cmd)
+	return cmd
+}
+
+func addLDPath(ctx context.Context, cmd *exec.Cmd) {
```
Comment (kaidaguerre) [inline db/db_local/backup.go:406]: add comment - why are we doing this
Change name to UpdateDynamicLibPath

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: db/db_local/backup.go (hunk 1 above)
Comment (binaek) [reply db/db_local/backup.go]: done
