### PR TITLE
Installation does not fail if the previous version of service could not be backed up. Closes #2014

### LINKED ISSUE #2014: Steampipe installation should not fail if old DB could not be backup up.

### PR DESCRIPTION
**Pull request by binaek**
Screenshot 2022-05-06 at 10 43 30 PM

### CODE REVIEW

**Comment by kaidaguerre** [comment]
Looks good. 

My suggestion for wording would be:

```
Warning: the Steampipe database has been upgraded from Postgres 12 to Postgres 14. Data in the public schema has not been migrated.

If you want to restore the contents of your public schema, please contact steampipe support.
```

File: db/db_local/install.go [hunk 1]
```diff
@@ -24,6 +25,18 @@ import (
 
 var ensureMux sync.Mutex
 
+func noBackupWarning() string {
+	warningMessage := `
```
Comment (kaidaguerre) [inline db/db_local/install.go:29]: warningMessage := `the Steampipe database has been upgraded from Postgres 12 to Postgres 14. Data in the public schema has not been migrated.

If you want to restore the contents of your public schema, please contact Steampipe support.`

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
