### PR TITLE
Fix issue where service tx hangs and introspection table disappear on timout. Closes #939

### LINKED ISSUE #939: When running controls, the expiry of the context used to run a query causing issues creating transactions, and seems to clear the session data
A couple of people have reported different symptoms

1) after the context expires, we are unable to create a transaction
```3 Ensure that any identity-based policies don't use wildcard actions ........................................................................................................  1 /  1 [=     ]
  | | 
  | ERROR: context deadline exceeded
  | 
  + 4 Enable S3 protection in GuardDuty to detect suspicious activities .........................................................................................................  1 /  1 [=     ]
  | | 
  | ERROR: error creating transaction - please restart Steampipe```

This suggests the database connection is blocked for come reason - prehaps and FDW crash/freeze

2) after the context expires, the session data is cleared meaning prepared statements cannot by found

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: db/db_local/create_client.go [hunk 1]
```diff
@@ -4,17 +4,31 @@ import (
...
 
-func createSteampipeDbClient() (*sql.DB, error) {
-	utils.LogTime("db.createSteampipeDbClient start")
-	defer utils.LogTime("db.createSteampipeDbClient end")
+func getLocalSteampipeConnectionString() (string, error) {
+	utils.LogTime("db.createDbClient start")
+	defer utils.LogTime("db.createDbClient end")
+
+	log.Println("[TRACE] createDbClient")
+	info, err := GetStatus()
```
Comment (kaidaguerre) [inline db/db_local/create_client.go:19]: lose blank line

File: utils/timing.go [hunk 2]
```diff
@@ -43,6 +43,9 @@ func LogTime(operation string) {
 	Timing = append(Timing, timeLog{time.Now(), elapsed, cumulative, operation})
 }
 
+func Trace(operation string) string { LogTime(fmt.Sprintf("%s start", operation)); return operation }
```
Comment (kaidaguerre) [inline utils/timing.go:46]: not loving the naming here

File: workspace/service_state.go [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+	"github.com/turbot/steampipe/db/db_common"
+	"github.com/turbot/steampipe/query/queryresult"
+	"github.com/turbot/steampipe/steampipeconfig/modconfig"
+	"github.com/turbot/steampipe/utils"
+)
+
+// EnsureServiceState queries the database and makes sure that workspace temp tables
+// and prepared statements are available in the database
+func EnsureServiceState(ctx context.Context, preparedStatementProviders *modconfig.WorkspaceResourceMaps, client db_common.Client) error {
+	defer utils.UnTrace(utils.Trace("workspace.EnsureServiceState"))
```
Comment (kaidaguerre) [inline workspace/service_state.go:15]: very confusing code

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: db/db_client/db_client.go [hunk 4]
```diff
@@ -104,6 +106,17 @@ func (c *DbClient) refreshDbClient() error {
 		return err
 	}
 	c.dbClient = db
+
+	// make sure that this new session is setup with the session
```
Comment (kaidaguerre) [inline db/db_client/db_client.go:110]: // setup the session data - prepared statements and introspection tables

File: db/db_client/db_client_execute.go [hunk 5]
```diff
@@ -144,10 +138,10 @@ func (c *DbClient) createTransaction(ctx context.Context, retryOnTimeout bool) (
 func (c *DbClient) startQuery(ctx context.Context, query string, tx *sql.Tx) (rows *sql.Rows, err error) {
 	doneChan := make(chan bool)
 	defer func() {
-		if err != nil && c.ensureSessionFunc != nil {
+		if err != nil {
 			// do this with a Background context, since the passed in context
```
Comment (kaidaguerre) [inline db/db_client/db_client_execute.go:142]: // if the underlying SQL client has certain errors (for example context expiry) it will reset the session
// restore the session data - prepared statements and introspection tables
// (do this with a Background context, since the passed in context may have expired)

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
