### PR TITLE
`plugin update` refactoring. Closes #216. Closes #234

### LINKED ISSUE #216: `steampipe plugin update --all` does not work.
`steampipe plugin update --all` reports that there are no updates, but there are updates. `steampipe plugin update aws gcp
` installs the updates successfully:

```
$ steampipe plugin list
┌─────────────────────────────────────────────────────┬─────────┬─────────────────────────────────────────────┐
│ NAME                                                │ VERSION │ CONNECTIONS                                 │
├─────────────────────────────────────────────────────┼─────────┼─────────────────────────────────────────────┤
│ hub.steampipe.io/plugins/turbot/aws@0.1             │         │                                             │
│ hub.steampipe.io/plugins/turbot/aws@latest          │ 0.5.0   │ aws,aws_pixie_aab,aws_morales,aws_pixie_aaa │
│ hub.steampipe.io/plugins/turbot/azure@latest        │         │ azure,azure_dmi,azure_morales_aaa           │
│ hub.steampipe.io/plugins/turbot/digitalocean@latest │ 0.1.0   │ digitalocean                                │
│ hub.steampipe.io/plugins/turbot/gcp@latest          │ 0.1.0   │ gcp_niteowl,gcp,gcp_morales                 │
│ hub.steampipe.io/plugins/turbot/github@latest       │ 0.0.5   │ github                                      │
│ hub.steampipe.io/plugins/turbot/google@latest       │ 0.0.1   │                                             │
│ hub.steampipe.io/plugins/turbot/ipstack@latest      │         │ ipstack                                     │
│ hub.steampipe.io/plugins/turbot/k8s@latest          │ local   │ k8s                                         │
│ hub.steampipe.io/plugins/turbot/slack@latest        │         │ slack                                       │
│ hub.steampipe.io/plugins/turbot/steampipe@latest    │ 0.0.2   │ steampipe                                   │
│ hub.steampipe.io/plugins/turbot/turbot@latest       │ local   │ turbot                                      │
│ hub.steampipe.io/plugins/turbot/whois@latest        │         │ whois                                       │
│ hub.steampipe.io/plugins/turbot/zendesk@latest      │         │ zendesk                                     │
└─────────────────────────────────────────────────────┴─────────┴─────────────────────────────────────────────┘

$ steampipe plugin update --all
All plugins are up to date.

$ steampipe plugin update aws gcp

Updated plugin: aws v0.5.1
Documentation:  https://hub.steampipe.io/plugins/turbot/aws

Updated plugin: gcp v0.1.1
Documentation:  https://hub.steampipe.io/plugins/turbot/gcp

```

### LINKED ISSUE #234: plugin update times out with > 10 plugins
currently the call to plugin update check url silently times out if sending a payload with > 10 plugins

We need to (some or all):
- increase timeout 
- report when failure occurs
- speed up the endpoint
- make the update check asyncronous - either report results at end of session or at start of next session

### PR DESCRIPTION
**Pull request by binaek89**

### CODE REVIEW

File: pluginmanager/pluginupdate.go [hunk 1]
```diff
@@ -39,10 +32,49 @@ type versionCheckPayload struct {
 
 // PluginVersionChecker :: wrapper struct over the plugin version check utilities
 type PluginVersionChecker struct {
```
Comment (kaidaguerre) [inline pluginmanager/pluginupdate.go:34]: rename to VersionChecker

File: pluginmanager/pluginupdate.go [hunk 2]
```diff
@@ -39,10 +32,49 @@ type versionCheckPayload struct {
...
-	signature string
+	pluginsToCheck []*versionfile.InstalledVersion
+	signature      string
+}
+
+// GetPluginUpdateReport :: looks up and reports the updated version of selective turbot plugins which are listed in versions.json
+func GetPluginUpdateReport(installationID string, check []*versionfile.InstalledVersion) map[string]VersionCheckReport {
+	pvc := new(PluginVersionChecker)
```
Comment (kaidaguerre) [inline pluginmanager/pluginupdate.go:41]: rename var to versionChecker

File: pluginmanager/pluginupdate.go [hunk 3]
```diff
@@ -39,10 +32,49 @@ type versionCheckPayload struct {
...
+			pvc.pluginsToCheck = append(pvc.pluginsToCheck, c)
+		}
+	}
+
+	return pvc.reportPluginUpdates()
+}
+
+// GetAllPluginUpdateReport :: looks up and reports the updated version of all turbot plugins which are listed in versions.json
+func GetAllPluginUpdateReport(installationID string) map[string]VersionCheckReport {
+	pvc := new(PluginVersionChecker)
```
Comment (kaidaguerre) [inline pluginmanager/pluginupdate.go:55]: rename var to versionChecker

File: cmd/plugin.go [hunk 4]
```diff
@@ -277,51 +288,89 @@ func runPluginUpdateCmd(cmd *cobra.Command, args []string) {
...
+		// we can't allow update and install at the same time
+		fmt.Println()
+		utils.ShowError(fmt.Errorf("%s cannot be used when updating specific plugins", constants.Bold("`--all`")))
+		fmt.Println()
+		cmd.Help()
+		fmt.Println()
+		return
+	}
+
+	updateSkipped := []updateSkip{}
```
Comment (kaidaguerre) [inline cmd/plugin.go:301]: var updateSkipped []updateSkip

File: cmd/plugin.go [hunk 5]
```diff
@@ -277,51 +288,89 @@ func runPluginUpdateCmd(cmd *cobra.Command, args []string) {
...
+	versionData, err := versionfile.Load()
+	if err != nil {
+		utils.ShowError(fmt.Errorf("error loading current plugin data"))
+		return
+	}
+	if versionData.Plugins == nil {
+		versionData.Plugins = map[string]*versionfile.InstalledVersion{}
+	}
+
+	runUpdatesFor := []*versionfile.InstalledVersion{}
```
Comment (kaidaguerre) [inline cmd/plugin.go:319]: var runUpdatesFor []*versionfile.InstalledVersion

File: cmd/plugin.go [hunk 6]
```diff
@@ -277,51 +288,89 @@ func runPluginUpdateCmd(cmd *cobra.Command, args []string) {
...
-			if report.Plugin.ImageDigest != report.CheckResponse.Digest {
-				plugins = append(plugins, fmt.Sprintf("%s/%s@%s", report.CheckResponse.Org, report.CheckResponse.Name, report.CheckResponse.Stream))
+			plugins = append(plugins, key)
+			runUpdatesFor = append(runUpdatesFor, v)
+		}
+	} else {
+		// get the args and retrieve the installed versions
+		for _, p := range plugins {
+			ref := ociinstaller.NewSteampipeImageRef(p)
+			isExists, _ := pluginmanager.IsPluginExists(p)
```
Comment (kaidaguerre) [inline cmd/plugin.go:334]: rename var to `exists`, `pluginmanager` package to `plugin` and  `IsPluginExists` to `Exists`, so:
```
exists, _ := plugin.Exists(p)
```

File: pluginmanager/pluginupdate.go [hunk 7]
```diff
@@ -39,10 +32,49 @@ type versionCheckPayload struct {
...
+		if strings.HasPrefix(p.Name, ociinstaller.DefaultImageRepoDisplayURL) {
+			pvc.pluginsToCheck = append(pvc.pluginsToCheck, p)
+		}
+	}
+
+	return pvc.reportPluginUpdates()
 }
 
-// CheckAndReportPluginUpdates ::
 func (pvc *PluginVersionChecker) reportPluginUpdates() map[string]VersionCheckReport {
```
Comment (kaidaguerre) [inline pluginmanager/pluginupdate.go:78]: `pvc -> v`

**Review by kaidaguerre — COMMENTED** [review]
rename `pluginmanager` package to `plugin`
rename `PluginVersionChecker` to `VersionChecker`

File: plugin/pluginmanager.go [hunk 8]
```diff
@@ -1,4 +1,4 @@
-package pluginmanager
+package plugin
```
Comment (kaidaguerre) [inline plugin/pluginmanager.go:1]: rename this file to `operations` or `actions`

File: plugin/pluginupdate.go [hunk 9]
```diff
@@ -1,4 +1,4 @@
-package pluginmanager
+package plugin
```
Comment (kaidaguerre) [inline plugin/pluginupdate.go:1]: rename this file to `versionchecker`

File: plugin/pluginmanager.go [hunk 10]
```diff
@@ -55,8 +55,8 @@ func Remove(image string, pluginConnections map[string][]string) error {
 	return v.Save()
 }
```
Comment (kaidaguerre) [inline plugin/pluginmanager.go:57]: add comment for Remove ::

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
