### PR TITLE
Fixes issue where table names with special characters are not handled correctly in auto-complete and `.inspect`. Closes #1109

### LINKED ISSUE #1109: Handle auto-complete for quoted identifiers
we should provide seamless handling of autocomplete for table names with spaces in

### PR DESCRIPTION
**Pull request by binaek**
```
binaeksarkar@Binaeks-MacBook-Pro ~ % steampipe query
Welcome to Steampipe v0.10.0-beta.2
For more information, type .help
> .inspect
+------------+---------------------------------------------------+
| connection | plugin                                            |
+------------+---------------------------------------------------+
| aws        | hub.steampipe.io/plugins/turbot/aws@latest        |
| chaos      | hub.steampipe.io/plugins/turbot/chaos@latest      |
| csv        | hub.steampipe.io/plugins/turbot/csv@latest        |
| hackernews | hub.steampipe.io/plugins/turbot/hackernews@latest |
| steampipe  | hub.steampipe.io/plugins/turbot/steampipe@latest  |
+------------+---------------------------------------------------+

To get information about the tables in a connection, run .inspect {connection}
To get information about the columns in a table, run .inspect {connection}.{table}

> 
> 
> .inspect csv
+----------+----------------------------------------------------+
| table    | description                                        |
+----------+----------------------------------------------------+
| dev test | CSV file at /Users/binaeksarkar/tests/dev test.csv |
+----------+----------------------------------------------------+

To get information about the columns in a table, run .inspect {connection}.{table}
	
> 
> 
> .inspect csv."dev test"
+--------+------+-------------+
| column | type | description |
+--------+------+-------------+
| col1   | text | Field 0.    |
| col2   | text | Field 1.    |
| col3   | text | Field 2.    |
+--------+------+-------------+
> 
> 
> .inspect "dev test"
+--------+------+-------------+
| column | type | description |
+--------+------+-------------+
| col1   | text | Field 0.    |
| col2   | text | Field 1.    |
| col3   | text | Field 2.    |
+--------+------+-------------+
> 
> 
> .exit
binaeksarkar@Binaeks-MacBook-Pro ~ % 
```

### CODE REVIEW

File: autocomplete/table.go [hunk 1]
```diff
@@ -47,7 +49,7 @@ func GetTableAutoCompleteSuggestions(schema *schema.Metadata, connectionMap *ste
 		// add qualified names of all tables
 		for tableName := range schemaDetails {
 			if !isTemporarySchema {
-				qualifiedTablesToAdd = append(qualifiedTablesToAdd, fmt.Sprintf("%s.%s", schemaName, tableName))
+				qualifiedTablesToAdd = append(qualifiedTablesToAdd, fmt.Sprintf("%s.%s", escapeIfRequired(schemaName), escapeIfRequired(tableName)))
```
Comment (kaidaguerre) [inline autocomplete/table.go:52]: no need to escape schema?

File: query/metaquery/handlers.go [hunk 2]
```diff
@@ -257,12 +257,23 @@ To get information about the columns in a table, run %s
 
 // inspect
 func inspect(input *HandlerInput) error {
+	fmt.Println("INPUT:", strings.Join(input.args(), "|"))
```
Comment (kaidaguerre) [inline query/metaquery/handlers.go:260]: remove logging

File: query/metaquery/definitions.go [hunk 3]
```diff
@@ -113,7 +113,7 @@ func init() {
 		constants.CmdInspect: {
 			title:       constants.CmdInspect,
 			handler:     inspect,
-			validator:   atMostNArgs(1),
+			validator:   atLeastNArgs(1),
```
Comment (kaidaguerre) [inline query/metaquery/definitions.go:116]: explain why we cannot use atMostNArgs even though we only want 1 arg

File: query/metaquery/handlers.go [hunk 4]
```diff
@@ -257,12 +257,23 @@ To get information about the columns in a table, run %s
...
 	}
-	// arg can be one of <connection_name> or <connection_name>.<table_name>
 	tableOrConnection := input.args()[0]
+	if len(input.args()) > 0 {
+		tableOrConnection = strings.Join(input.args(), " ")
+	}
+	// arg can be one of <connection_name> or <connection_name>.<table_name>
 	split := strings.Split(tableOrConnection, ".")
+	for i, s := range split {
+		s = strings.TrimSpace(s)
```
Comment (kaidaguerre) [inline query/metaquery/handlers.go:271]: // trim escaping

File: query/metaquery/utils.go [hunk 5]
```diff
@@ -41,15 +42,18 @@ func splitByWhitespace(str string) (s []string) {
 	csvDecoder.TrimLeadingSpace = true
 	// Read can never error, because we are passing in a StringReader
 	// lookup csv.Reader.Read
-	split, _ := csvDecoder.Read()
+	split, err := csvDecoder.Read()
+	if err != nil {
+		log.Println("[WARN]", err)
+	}
```
Comment (kaidaguerre) [inline query/metaquery/utils.go:48]: is this error handling needed? if so do it properly

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
