### PR TITLE
Fix to display timing profile data when appropriate env var is set.  Closes #513

### LINKED ISSUE #513: get time logging working again

### PR DESCRIPTION
**Pull request by binaek89**

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -7,30 +7,31 @@ import (
...
 	"github.com/turbot/steampipe/cmd"
 	"github.com/turbot/steampipe/utils"
 )
 
 var Logger hclog.Logger
 
 func main() {
-	logging.LogTime("main start")
+	utils.LogTime("main start")
+	exitCode := 0
```
Comment (kaidaguerre) [inline main.go:18]: there is a global exit code in root, so use that.

And this code in root: 

```
func Execute() {
	rootCmd.Execute()
	os.Exit(exitCode)
}
```
maybe that just needs to be a defer

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: main.go (hunk 1 above)
Comment (binaek89) [reply main.go:18]: If we exit from `root.go` then the `defer` in `main.go` doesn't fire and the `DisplayProfileData` function is never executed.
