### PR TITLE
Fixes issue where a `check` cancel was not waiting for query cancellation to finish. Closes #1171

### LINKED ISSUE #1171: Cancelling `check` leaves `implicit service` running.
When a `check` run is cancelled (using `ctrl+c`) - the `service` that it started (if at all) is left running and doesn't shut down.

### PR DESCRIPTION
**Pull request by binaek**

### CODE REVIEW

File: control/controlexecute/execution_tree.go [hunk 1]
```diff
@@ -99,8 +99,16 @@ func (e *ExecutionTree) Execute(ctx context.Context, client db_common.Client) in
 	// just execute the root - it will traverse the tree
 	e.Root.Execute(ctx, client, parallelismLock)
 
-	// wait till we can acquire all semaphores - meaning that all runs have finished
-	parallelismLock.Acquire(ctx, maxParallelGoRoutines)
+	executeFinishWaitCtx := ctx
+	if ctx.Err() != nil {
+		// use a Background context - since the original context has been cancelled
+		// this lets us wait for the active control queries to cancel
+		c, cancel := context.WithTimeout(context.Background(), 30*time.Second)
```
Comment (kaidaguerre) [inline control/controlexecute/execution_tree.go:106]: timeout in a const

File: constants/control_execute.go [hunk 2]
```diff
@@ -3,3 +3,6 @@ package constants
 // ParallelControlMultiplier is used to determine the nbumber of goroutines to start for the control run
 // this is a multiplier for the max db connections which are configred
 const ParallelControlMultiplier = 3
+
+// The maximum number of seconds to wait for control queries to finish cancelling
+const MaxQueryCancellationTimeout = 30
```
Comment (kaidaguerre) [inline constants/control_execute.go:8]: const QueryCancellationTimeout = 30*time.Second

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
