### PR TITLE
Steampipe should return file not found as error when the input file does not exist. Closes #1752

### LINKED ISSUE #1752: Running 'steampipe query file_not_found.sql' should return a file not found error
I was very confused for a while today when putting Steampipe inside a cronjob and I hadn't set the current working directory properly.

Steampipe returns SQL errors if the file is not found ... so I kept checking my SQL code.

I wish Steampipe would detect that the input is in the shape of a file name and then return a file not found error instead?

```
/tmp/crap $ ls -al
total 0
drwxr-xr-x   2 nathan  wheel    64 Mar 29 10:58 .
drwxrwxrwt  38 root    wheel  1216 Mar 29 10:59 ..
/tmp/crap $ 
/tmp/crap $ steampipe query test.sql
Warning: executeQueries: query 1 of 1 failed: ERROR: syntax error at or near "test" (SQLSTATE 42601)

/tmp/crap $ 
/tmp/crap $ steampipe query /tmp/crap/test.sql
Warning: executeQueries: query 1 of 1 failed: ERROR: syntax error at or near "/" (SQLSTATE 42601)

/tmp/crap $ 
```

### PR DESCRIPTION
**Pull request by pskrbasu**
- file not found
Screenshot 2023-08-25 at 2 29 56 PM

- empty file
Screenshot 2023-08-25 at 4 35 24 PM

- query resource not found in mod
Screenshot 2023-08-25 at 4 36 44 PM

- cant open file
Screenshot 2023-08-25 at 5 56 53 PM

### CODE REVIEW

File: pkg/workspace/workspace_queries.go [hunk 1]
```diff
@@ -66,24 +66,36 @@ func (w *Workspace) ResolveQueryAndArgsFromSQLString(sqlString string) (*modconf
...
 	// 2) is this a file
-	fileQuery, fileExists, err := w.getQueryFromFile(sqlString)
+	// get absolute filename
+	filePath, err := filepath.Abs(sqlString)
+	if err != nil {
+		return nil, nil, fmt.Errorf("error opening file '%s': %s", sqlString, err.Error())
+	}
+	fileQuery, fileExists, err := w.getQueryFromFile(filePath)
 	if fileExists {
 		if err != nil {
```
Comment (kaidaguerre) [inline pkg/workspace/workspace_queries.go:76]: move error check before `if fileExists `

File: pkg/workspace/workspace_queries.go [hunk 2]
```diff
@@ -66,24 +66,36 @@ func (w *Workspace) ResolveQueryAndArgsFromSQLString(sqlString string) (*modconf
...
+			return nil, nil, fmt.Errorf("error opening file '%s': %s", filePath, err.Error())
 		}
 		if fileQuery == nil {
-			error_helpers.ShowWarning(fmt.Sprintf("file '%s' does not contain any data", sqlString))
+			error_helpers.ShowWarning(fmt.Sprintf("file '%s' does not contain any data", filePath))
 			// (just return the empty query - it will be filtered above)
 		}
 		return fileQuery, nil, nil
 	}
+	// sqlString is not a file name that exists
```
Comment (kaidaguerre) [inline pkg/workspace/workspace_queries.go:85]: `// sqlString is not a file name that exists` => `// the argument cannot be resolved as an existing file`

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
can we have screenshots of the various errors
