### PR TITLE
Fixes inconsistent output for `service` commands with `--dashboard`. Closes #1599

### LINKED ISSUE #1599: `service` output with `dashboard`
* `service start` produces inconsistent output when used with `--dashboard`
* `service stop` shows only database service was stopped

### PR DESCRIPTION
**Pull request by binaek**
## `service start`
Screenshot 2022-03-09 at 8 46 40 PM

## `service start` (service already running
Screenshot 2022-03-09 at 8 47 11 PM
)

## `service start --dashboard`
Screenshot 2022-03-09 at 8 46 13 PM

## `service start --dashboard` (already running)
Screenshot 2022-03-09 at 8 47 35 PM

### CODE REVIEW

File: cmd/service.go [hunk 1]
```diff
@@ -573,7 +576,7 @@ func getServiceProcessDetails(process *psutils.Process) (string, string, string,
 	return fmt.Sprintf("%d", process.Pid), installDir, port, listenType
 }
 
-func printStatus(ctx context.Context, dbState *db_local.RunningDBInstanceInfo, pmState *pluginmanager.PluginManagerState, dashboardState *dashboardserver.DashboardServiceState) {
+func printStatus(ctx context.Context, dbState *db_local.RunningDBInstanceInfo, pmState *pluginmanager.PluginManagerState, dashboardState *dashboardserver.DashboardServiceState, addAlready bool) {
```
Comment (kaidaguerre) [inline cmd/service.go:579]: rename `addAlready` to `alreadyRunning`

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
