### PR TITLE
fixes spinner new line issue for long texts. Closes #450

### LINKED ISSUE #450: Spinner displays multiple newlines if spinner text is wider than the terminal
for example 
```
steampipe check aws.control_group.cis_v130
```
with a narrow screen

### PR DESCRIPTION
**Pull request by binaek89**
spinner displays a new line on every refresh if the text given as suffix to the spinner exceeds the current terminal width.

this fix truncates the suffix to the maximum available width and appends ellipsis at the end

### CODE REVIEW

File: display/spinner.go [hunk 1]
```diff
@@ -10,16 +10,27 @@ import (
...
 
+//
+// spinner format:
+// <spinner><space><message><space><dot><dot><dot><cursor>
+// 		1	   1   [.......]   1     1    1    1     1
+// We need at least seven characters to show the spinner properly
+//
+// Not using the (…) character, since it is too small
+//
+const mustHaveCharLengthForSpinner = 7
```
Comment (kaidaguerre) [inline display/spinner.go:21]: rename to minSpinnerWidth

File: display/spinner.go [hunk 2]
```diff
@@ -10,16 +10,27 @@ import (
...
+
 func truncateSpinnerMessageToScreen(msg string) string {
 	if len(strings.TrimSpace(msg)) == 0 {
 		// if this is a blank message, return it as is
 		return msg
 	}
+
 	maxCols, _, _ := gows.GetWinSize()
-	if maxCols < 7 {
+	if maxCols < mustHaveCharLengthForSpinner {
```
Comment (kaidaguerre) [inline display/spinner.go:30]: so is this check saying - 
```
if the screen is smaller than the minimum spinner width, we cannot truncate to make it fit
```

if so, let's add that as a comment
