### PR TITLE
Fix the in-place switch over to ARM for plugins . Closes #1880

### LINKED ISSUE #1880: Fix the in-place switch over to ARM for plugins

### PR DESCRIPTION
**Pull request by pskrbasu**

### CODE REVIEW

File: task/pluginversioncheck.go [hunk 1]
```diff
@@ -63,13 +63,17 @@ func pluginNotificationMessage(reports []plugin.VersionCheckReport) []string {
 				constants.Bold(report.CheckResponse.Version),
 			)
 		} else {
+			version := report.CheckResponse.Version
 			format := fmt.Sprintf("  %%-%ds @ %%-10s       %%10s → %%-10s", longestNameLength)
+			if report.Plugin.Version == report.CheckResponse.Version {
+				version = fmt.Sprintf("%s (arm64)", version)
```
Comment (kaidaguerre) [inline task/pluginversioncheck.go:69]: add a comment  - why are we doing this?

File: plugin/update.go [hunk 2]
```diff
@@ -17,7 +17,7 @@ func SkipUpdate(report VersionCheckReport) (bool, string) {
 	}
 
 	// 2) If we are M1, current installed version is AMD, and ARM is available - update
-	if isRunningAsMacM1() && report.Plugin.BinaryArchitecture == constants.ArchARM64 && manifestHasM1Binary(report.CheckResponse.Manifest) {
+	if isRunningAsMacM1() && manifestHasM1Binary(report.CheckResponse.Manifest) && report.Plugin.BinaryArchitecture != constants.ArchARM64 {
```
Comment (kaidaguerre) [inline plugin/update.go:20]: reverse logic of SkipUpdate and call it ShouldUpdate

negative bools are always a bit confusing

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
